### ISSUE TITLE
Possible bug in world 2?

### ISSUE THREAD

**Issue by aznlir88** [captainsouthbird/3Mix#2]
A question, in world 2 there is a square level just below stage 1. I only got 2 out of 3 stars there and would like to get them all.

Whole game is completed hardest parts almost done with comets but i wonder would i ever be able to replay this level and get all stars as i cannot re-enter this level.

Is it possible or a bug?

Ps. sorry for copy paste from romhacking forums but got no answer there.

**Comment by captainsouthbird** [comment]
I'm not sure what you mean. I just ran through 2-1 and found all the star coins. If you're playing on an emulator, can you send me the save data file, or a save state or something?

**Comment by aznlir88** [comment]
Hi no problem but i mean this level. As i wrote "just below stage 1", not stage 1 itself.

I attach photo but if you need savefile i can provide it as well.
![IMG_20230612_121550](https://github.com/captainsouthbird/3Mix/assets/72318429/b3d38142-7a08-4ef1-85b6-15ff5c3efada)

**Comment by captainsouthbird** [comment]
Yeah that is peculiar because that tile was a Toad House / card mini-game, it should not have any stars associated with it at all. Something strange seems to be happening. I probably will need a save file to understand this.

**Comment by aznlir88** [comment]
No worries will provide it within a day as i do not have 24h access to hardware.

Yet talking about it a bit more - i remember, if my memory is not playing tricks on me - that it was just a level i was able to collect stars in and i decided i will just return and get all of them later.

And not related but maybe similiar a bit as i play 2 player mode most of the time (not always) on that save file i remember when i was doing comet levels in world 8 and 2nd player was having fun with world 1 easy levels i failed in one level and it happened to be my "turn" to play again and here i am not sure but either i got his checkpoint or his entire world 1 level from his checkpoint and it accepted stars i collected from "his" world 1 level as my world 8 comet level. Not sure now it only happened once but 100% sure that happened and it made my life easier.

I suppose there may be something not working quite well when playing 2 player mode.

ps. Any plans to add 3 player support via nes four score support? Or adding peach and 4 player support. I know it is a lot but it would totally rock.

ps2. as i said i will provide save file later.

**Comment by aznlir88** [comment]
[save.sav.zip](https://github.com/captainsouthbird/3Mix/files/11733725/save.sav.zip)
Guess that is the file. I was playing rev2b version so should be ok, on fceux.

Is there a way you can fix that save file for me and upload fixed one?

**Comment by aznlir88** [comment]
Any update?

**Comment by captainsouthbird** [comment]
[save.zip](https://github.com/captainsouthbird/3Mix/files/11787845/save.zip)

I've manually patched out the star coins that shouldn't have been attributed to a Toad House. I don't know what might've caused the original issue. But counting out remaining objectives on World 2 I think you should be good with this modified save. Let me know if you see any other anomalies.

For my own record, patched RAM $7D5C with value $10 to indicate completed without Star Coins

**Comment by aznlir88** [comment]
Thank you, but if i am correct something is not quite right. I see coins removed from mashroom house level and that is ok.

Yet i counted and if i remember correctly there are 12 missing coins in this world and through comets and missed coins i will only be able to get 9 or something like that.

Please correct me if i am wrong but it does not seem right as far as i understand the situation.

**Comment by captainsouthbird** [comment]
You have 19/31, total missing = 12

2-3 comet +1 = 1
Fortress comet +1, missing star coin +1 = 2
2-4 comet +1, missing star coin +1 = 2
2-5 missing star coin +1 = 1
Ghost house missing all star coins = 3
Airship missing all star coins = 3

1 + 2 + 2 + 1 + 3 + 3 = 12

Note that you can't get the "regular" star coins while a comet is active, so you'll have to complete comets first where they overlap.

Happy hunting

**Comment by aznlir88** [comment]
Oooook, i forgot about airship. Thank you.

**Comment by captainsouthbird** [comment]
Closing under the assumption there's nothing else I can do. No idea how the data got corrupted in the first place, but was able to work around.
